"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Search, ArrowRight, PackageSearch } from "lucide-react";

type Product = { id: string; name: string; type: string; category: string; modelName: string | null; modelNumber: string | null; brand: { name: string; slug: string }; _count: { complaints: number } };

export default function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/products").then((response) => response.json()).then((data) => setProducts(Array.isArray(data) ? data : data.products || [])).finally(() => setLoading(false)); }, []);
  const visible = products.filter((product) => `${product.name} ${product.type} ${product.category} ${product.modelName || ""} ${product.modelNumber || ""} ${product.brand.name}`.toLowerCase().includes(search.toLowerCase()));
  return <main className="min-h-screen bg-slate-50"><section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-widest text-orange-600">Product directory</p><h1 className="mt-2 text-4xl font-black tracking-tight">Search products and brands</h1><p className="mt-3 max-w-2xl text-slate-600">Find a product’s public complaint history by brand, type, category, model name, or model number. This directory is for research, not shopping.</p><div className="relative mt-8 max-w-2xl"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><label htmlFor="product-search" className="sr-only">Search products</label><input id="product-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search brand, product, model..." className="w-full rounded-xl border border-slate-300 bg-white py-4 pl-12 pr-4 text-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100" /></div></div></section><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">{loading ? <p className="py-20 text-center text-slate-500">Loading products...</p> : visible.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center"><PackageSearch className="mx-auto h-10 w-10 text-slate-400" /><h2 className="mt-4 font-bold">No matching products</h2><p className="mt-2 text-sm text-slate-500">Try a different search or file a complaint to add a product.</p></div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((product) => <Link key={product.id} href={`/products/${product.brand.slug}/${product.id}`} className="group rounded-xl border border-slate-200 bg-white p-5 shadow-sm hover:border-teal-300 hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-800">{product.category}</span><ArrowRight className="h-4 w-4 text-slate-400 group-hover:text-teal-700" /></div><h2 className="mt-5 text-lg font-extrabold">{product.name}</h2><p className="mt-1 text-sm font-semibold text-slate-600">{product.brand.name} · {product.type}</p><p className="mt-3 text-xs text-slate-500">{product.modelNumber || product.modelName || "Model details not provided"}</p><p className="mt-5 text-xs font-bold uppercase tracking-wide text-orange-600">{product._count.complaints} complaint records</p></Link>)}</div>}</section></main>;
}
